#Install Library

In [ ]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.4-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.4

In [ ]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.23.5)

#Import library

In [ ]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [ ]:
#scrape all available reviews
from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
'com.gojek.app',
lang = 'id',
country ='id',
sort=Sort.NEWEST,
count=10000,
filter_score_with=None

)

#Show Data yang sudah di crawling

In [ ]:
df_busu = pd.DataFrame(np.array(result),columns=['review']) #nama file bebas
df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))
df_busu.tail()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
9995,bd46c79e-43f8-402d-a963-9ebfae523c97,Tata Handayani,https://play-lh.googleusercontent.com/a-/ALV-U...,Sumpah lagi bnr2 gak punya duit buat beli kuot...,5,0,4.75.1,2023-09-26 08:06:24,None,NaT,4.75.1
9996,a03fec71-0e17-4034-86d7-c3670099821f,Aldy Hidayat (#Badayy),https://play-lh.googleusercontent.com/a-/ALV-U...,"Layanan cs kurang baik, ~Terimakasih.",1,0,None,2023-09-26 08:04:54,"Hai Aldy Hidayat, mohon maaf atas ketidaknyama...",2023-09-26 08:39:33,None
9997,88d94548-6ca7-446c-a0bc-693a75ff937e,Tania Yulyanti,https://play-lh.googleusercontent.com/a-/ALV-U...,"Aplikasi yang sangat bagus , membantu saat kes...",5,0,4.75.1,2023-09-26 07:55:02,None,NaT,4.75.1
9998,1cc03ee2-1145-4674-9e84-f7eb48748837,Uliana Ezra,https://play-lh.googleusercontent.com/a/ACg8oc...,bgus,4,0,4.75.1,2023-09-26 07:52:55,None,NaT,4.75.1
9999,93896af3-71c5-4b58-b5d3-a364ee2bb0aa,Ario Pandu,https://play-lh.googleusercontent.com/a/ACg8oc...,Sangat membantu,5,0,4.75.1,2023-09-26 07:48:58,None,NaT,4.75.1

In [ ]:
len(df_busu.index)

10000

#ambil data yang dibutuhkan

In [ ]:
df_busu[['userName', 'score', 'at', 'content']].tail()

,userName,score,at,content
9995,Tata Handayani,5,2023-09-26 08:06:24,Sumpah lagi bnr2 gak punya duit buat beli kuot...
9996,Aldy Hidayat (#Badayy),1,2023-09-26 08:04:54,"Layanan cs kurang baik, ~Terimakasih."
9997,Tania Yulyanti,5,2023-09-26 07:55:02,"Aplikasi yang sangat bagus , membantu saat kes..."
9998,Uliana Ezra,4,2023-09-26 07:52:55,bgus
9999,Ario Pandu,5,2023-09-26 07:48:58,Sangat membantu

In [ ]:
my_df = df_busu[['userName', 'score', 'at', 'content']]

In [ ]:
#simpan dataset ke dalam file
my_df.to_csv("DataSetGojek.csv", index = False)