In [ ]:
!pip install pandas
!pip install numpy
!pip install nltk

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.23.5)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2023.6.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.1)

In [ ]:
#untuk komputasi numerik
import numpy as pd

#memproses pengolahan text
import nltk

#membantu mempermudah manipulasi data teks
import string

#mencari pola kata spesifik yang dicari
import re

#hilangkan notif karena migrasi dari python
import warnings
warnings.filterwarnings('ignore')

# New Section

# New Section

In [ ]:
#import Library yang dibutuhkan
import pandas as pd
from tqdm import tqdm, notebook
import warnings
warnings.filterwarnings('ignore')

pd.pandas.set_option('display.max_columns', None)
pd.pandas.set_option('display.max_rows', None)
pd.pandas.set_option('display.max_colwidth', None)
pd.pandas.set_option('display.width', None)

In [ ]:
df = pd.read_csv('/content/DataSetGojek.csv')
df.head()

,userName,score,at,content
0,Namanya Ayang,1,2023-11-08 10:38:23,Download lama banget loh
1,Rezki Awan,2,2023-11-08 10:36:18,drivers food nya pada g jelas
2,Bayu Langit,1,2023-11-08 10:32:41,"Sistem gojek makin kesini makin kacau !!!! Kasian drivernya, aplikasi tanpa rasa kemanusiaan !!!"
3,Imong Fadhlurrahman,5,2023-11-08 10:32:12,akurat
4,Efi Juhaefi,1,2023-11-08 10:20:53,Mo transfer di suruh upgrade Giliran upgrade gagal mulu Ga jelas banget

In [ ]:
df['sentiment'] = df['score'].map({1.0:0,2.0:0,3.0:1, 4.0:1, 5.0:1})

In [ ]:
#Ambil teks aja untuk kita labelkan
dataku = pd.DataFrame(df[['content','sentiment']])
dataku.head(10)

,content,sentiment
0,Download lama banget loh,0
1,drivers food nya pada g jelas,0
2,"Sistem gojek makin kesini makin kacau !!!! Kasian drivernya, aplikasi tanpa rasa kemanusiaan !!!",0
3,akurat,1
4,Mo transfer di suruh upgrade Giliran upgrade gagal mulu Ga jelas banget,0
5,"Tolong perbaiki, setelah update bukan baik malah aneh-aneh, masa belum tekan untuk memesan, nih aplikasi malah mesan sendiri dan gojek yang datang malah dua akibat aplikasi lucu ini mesen sendiri, sekarang yang rugi siapa ? Aku kan, karna udah kepotong. TOLONG PERBAIKI KEMBALI !!!.",0
6,ok baik,1
7,Gojek Oke,1
8,Bagus sekali cepat,1
9,Tetap semangat ✊,0

from matplotlib import pyplot as plt
_df_0['sentiment'].plot(kind='hist', bins=20, title='sentiment')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['sentiment'].plot(kind='line', figsize=(8, 4), title='sentiment')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
my_df = dataku[['content','sentiment']]

In [ ]:
#simpan Dataset ke dalam File
my_df.to_csv("label_gojek.csv", index = False)