#Install and Import Library

In [ ]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install nltk
!pip install sastrawi

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.23.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.44.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (0.12.2)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in /usr/local/lib/python3.10/dist-packages (from seaborn) (1.23.5)
Requirement already satisfied: pandas>=0.25 in /usr/local/lib/python3.10/dist-packages (from seaborn) (1.5.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in /usr/local/lib/python3.10/dist-packages (from seaborn) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.44.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25->seaborn) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2023.6.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.1)
Requirement already satisfied: sastrawi in /usr/local/lib/python3.10/dist-packages (1.0.1)

In [ ]:
#untuk komputasi numerik
import numpy as np

#memproses pengolahan text
import nltk

#membantu mempermudah manipulasi data teks
import string

#mencari pola kata spesifik yang dicari
import re

#hilangkan notif krn migrasi dari python
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#import library yang dibutuhkan
import pandas as pd
from tqdm import tqdm, notebook
warnings.filterwarnings('ignore')
pd.pandas.set_option('display.max_columns',None)
pd.pandas.set_option('display.max_rows',None)
pd.pandas.set_option('display.max_colwidth',None)
pd.pandas.set_option('display.width',None)

#Memasukkan Dataset

In [ ]:
df = pd.read_csv('/content/label_gojek.csv')

#Praproses Data

In [ ]:
#konversi ke lowercase
df['content'] = df['content'].apply(lambda x: " ".join(x.lower() for x in x.split()))
df.head()

,content,sentiment
0,download lama banget loh,0
1,drivers food nya pada g jelas,0
2,"sistem gojek makin kesini makin kacau !!!! kasian drivernya, aplikasi tanpa rasa kemanusiaan !!!",0
3,akurat,1
4,mo transfer di suruh upgrade giliran upgrade gagal mulu ga jelas banget,0

#Menghapus angka,simbol dan emoji

In [ ]:
#Menghilangkan angka
df['content'] = df['content'].str.replace('[0-9]+','')

#Menghilangkan punctuations = tandabaca ex:@,_.#,etc dan emoji
df['content'] = df['content'].str.replace('[^\w\s]+','',)
df.head(30)

,content,sentiment
0,download lama banget loh,0
1,drivers food nya pada g jelas,0
2,sistem gojek makin kesini makin kacau kasian drivernya aplikasi tanpa rasa kemanusiaan,0
3,akurat,1
4,mo transfer di suruh upgrade giliran upgrade gagal mulu ga jelas banget,0
5,tolong perbaiki setelah update bukan baik malah anehaneh masa belum tekan untuk memesan nih aplikasi malah mesan sendiri dan gojek yang datang malah dua akibat aplikasi lucu ini mesen sendiri sekarang yang rugi siapa aku kan karna udah kepotong tolong perbaiki kembali,0
6,ok baik,1
7,gojek oke,1
8,bagus sekali cepat,1
9,tetap semangat,0
10,memang oke,1
11,ok,1
12,oke,1
13,ok,1
14,produk indonesia harus didukung,1
15,aplikasi sangat bagus sekali bisa buat pesan mobil motor makanan dan bisa melakukan pembayaran dan pembelian pulsa dan paket data,1
16,gopay pinjam di tolak ajapadahal driver gojek juga butuhkenapa sulit sih kan jelas kalo dicek akun nya sama dengan akun go partner,1
17,bingung mau makan enak di mana cari di gofood dan dapatkan berbagai menu terbaru nikmat banyak diskon,1
18,sangat membantu,1
19,wahai para costumer tahukan anda bahwa driver food cuma di bayar rupiah sama aplikator sedangkan kalian bayar sampai rb ke aplikasi bagaimana nasih driver coba bayangkan padahal aplikator udah untung banyak untung dari driver untung dari costumer biaya layanan untung dari merchant management gojek yg sekarang rakus,0
20,bagus,1
21,ok,1
22,kurangin dulu bintangnya ada paylater gabisa dipake sama sekali padahal limit full gaada tagihan aplikasi suka lag kalau dibuka,1
23,error terus kayaknya mau nyoba pindah ke grab,0
24,kaga menguntungkan,0
25,orang nya baik,1
26,saat ini merasa puas good lanjutkan,1
27,aplikasinya sangat bermanfaat memudahkan mobilitas dan harganya bersaing mantap ni aplikasinya,1
28,tolong dong itu gofood disurvei toko banyak yang udah ga jualan tapi masih ada di list trus masih terima pesenan mending diilangin dari list,0
29,gudd boy,1

#Removing Stopwords

In [ ]:
#stopwords menggunakan sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
stopwords_id = factory.get_stop_words()

def remove_stopwords(text):
  """custom function to remove the stopwords"""
  return " ".join([word for word in str(text).split() if word not in stopwords_id])

df["content"] = df["content"].apply(lambda text:remove_stopwords(text))
df.head()

                                                                            content  sentiment
0                                                          download lama banget loh          0
1                                                          drivers food nya g jelas          0
2  sistem gojek makin kesini makin kacau kasian drivernya aplikasi rasa kemanusiaan          0
3                                                                            akurat          1
4              mo transfer suruh upgrade giliran upgrade gagal mulu ga jelas banget          0

#Stemming

In [ ]:
from Sastrawi.Stemmer.Stemmer import Stemmer
#Stemming Bahasa Indonesia
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
Stemmer_id = factory.create_stemmer()

def stem_words(text):
  return " ".join([Stemmer_id.stem(word) for word in text.split()])

df["content"] = df["content"].apply(lambda text: stem_words(text))
df.head()

                                                                      content  sentiment
0                                                    download lama banget loh          0
1                                                    drivers food nya g jelas          0
2  sistem gojek makin kesini makin kacau kasi drivernya aplikasi rasa manusia          0
3                                                                      akurat          1
4          mo transfer suruh upgrade gilir upgrade gagal mulu ga jelas banget          0

#Tokenize

In [ ]:
#Tokenization bertujuan mengubah kata ke dalam unit terkecil bermakna
def tokenize_text(text):
  tokenized_text = text.split()
  return tokenized_text
df['content'] = df['content'].apply(lambda x:tokenize_text(x))
df.head()

,content,sentiment
0,"[download, lama, banget, loh]",0
1,"[drivers, food, nya, g, jelas]",0
2,"[sistem, gojek, makin, kesini, makin, kacau, kasi, drivernya, aplikasi, rasa, manusia]",0
3,[akurat],1
4,"[mo, transfer, suruh, upgrade, gilir, upgrade, gagal, mulu, ga, jelas, banget]",0

#Lemmatize

In [ ]:
#Lemmatization
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
def lemmatize_text(token_list):
    return " ".join([lemmatizer.lemmatize(token) for token in token_list if not token in set()])

lemmatizer = nltk.stem.WordNetLemmatizer()
df['content'] = df['content'].apply(lambda x: lemmatize_text(x))
df.head()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

                                                                      content  sentiment
0                                                    download lama banget loh          0
1                                                     driver food nya g jelas          0
2  sistem gojek makin kesini makin kacau kasi drivernya aplikasi rasa manusia          0
3                                                                      akurat          1
4          mo transfer suruh upgrade gilir upgrade gagal mulu ga jelas banget          0

#Simpan Dataset yang sudah dibersihkan

In [ ]:
my_df = df[['content','sentiment']]

In [ ]:
#simpan Dataset ke dalam File
my_df.to_csv("reviews_gojek_databersih.csv", index = False)